module.exports={
  NAME_OR_PASSWORD_IS_REQUIRED :"NAME_OR_PASSWORD_IS_REQUIRED",
  USER_IS_ALREADY_EXIST:"USER_IS_ALREADY_EXIST",
  USER_IS_NOT_EXIST:"USER_IS_NOT_EXIST",
  PASS_IS_INCORRENT:"PASS_IS_INCORRENT",
  UNAUTHORIZATION:"UNAUTHORIZATION",
  OPERATION_IS_NOT_ALLOWED:"OPERATION_IS_NOT_ALLOWED"
}